[phases.setup]
nixPkgs = ['ffmpeg', 'nodejs_20', 'pnpm', 'pkg-config', 'cairo', 'pango', 'libjpeg', 'giflib', 'librsvg', 'python3', 'gcc', 'binutils', 'node-gyp']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile',
  'echo "Attempting to rebuild canvas explicitly..."',
  'pnpm rebuild canvas --verbose > /app/canvas_rebuild.log 2>&1 || true',
  'echo "Contents of canvas_rebuild.log:"',
  'cat /app/canvas_rebuild.log || echo "canvas_rebuild.log not found or empty"',
  # Diagnostic commands to check if canvas.node was built
  '''\
  echo "Checking for canvas.node after pnpm install and rebuild attempt..."; \
  CANVAS_PATH_PATTERN="node_modules/.pnpm/canvas@*/node_modules/canvas/build/Release/canvas.node"; \
  # Try to find the canvas.node file in the entire /app directory first
  FOUND_CANVAS_NODE_ABS=$(find /app -name canvas.node -print -quit); \
  if [ -n "$FOUND_CANVAS_NODE_ABS" ]; then \
    echo "Found canvas.node at absolute path: $FOUND_CANVAS_NODE_ABS"; \
    echo "Running ldd on $FOUND_CANVAS_NODE_ABS:"; \
    ldd "$FOUND_CANVAS_NODE_ABS" || echo "ldd command failed on $FOUND_CANVAS_NODE_ABS"; \
  else \
    echo "canvas.node NOT found anywhere in /app with find -name canvas.node"; \
    echo "Checking specific pnpm pattern: $CANVAS_PATH_PATTERN"; \
    FOUND_CANVAS_NODE_PATTERN=$(find /app -path "$CANVAS_PATH_PATTERN" -print -quit); \
    if [ -n "$FOUND_CANVAS_NODE_PATTERN" ]; then \
        echo "canvas.node found with pattern at $FOUND_CANVAS_NODE_PATTERN"; \
        echo "Running ldd on $FOUND_CANVAS_NODE_PATTERN:"; \
        ldd "$FOUND_CANVAS_NODE_PATTERN" || echo "ldd command failed on $FOUND_CANVAS_NODE_PATTERN"; \
    else \
        echo "canvas.node NOT found with pattern $CANVAS_PATH_PATTERN"; \
        echo "Listing contents of potential canvas directories in .pnpm:"; \
        ls -R /app/node_modules/.pnpm/canvas@* || echo "Failed to list canvas directories in .pnpm"; \
        echo "Listing contents of /app/node_modules/canvas if it exists:"; \
        ls -R /app/node_modules/canvas || echo "/app/node_modules/canvas not found or failed to list"; \
    fi; \
  fi
  '''
]

[phases.start]
cmd = 'pnpm start'