[phases.setup]
nixPkgs = [
  'ffmpeg',
  'nodejs_20',
  'pnpm',
  'pkg-config', # Required by canvas
  'cairo',      # Required by canvas
  'pango',      # Required by canvas
  'libjpeg',    # Required by canvas
  'giflib',     # Required by canvas
  'librsvg'     # Required by canvas
]
cmds = ['npm install -g pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']