[phases.setup]
nixPkgs = ['ffmpeg', 'nodejs_20', 'pnpm', 'pkg-config', 'cairo', 'pango', 'libjpeg', 'giflib', 'librsvg', 'python3', 'gcc', 'binutils', 'node-gyp']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile',
  # Diagnostic commands to check if canvas.node was built
  '''\
  echo "Checking for canvas.node after pnpm install..."; \
  CANVAS_PATH_PATTERN="node_modules/.pnpm/canvas@*/node_modules/canvas/build/Release/canvas.node"; \
  find /app -path "$CANVAS_PATH_PATTERN" -print -quit; \
  FOUND_CANVAS_NODE=$(find /app -path "$CANVAS_PATH_PATTERN" -print -quit); \
  if [ -n "$FOUND_CANVAS_NODE" ]; then \
    echo "canvas.node found at $FOUND_CANVAS_NODE"; \
    echo "Running ldd on $FOUND_CANVAS_NODE:"; \
    ldd "$FOUND_CANVAS_NODE" || echo "ldd command failed on $FOUND_CANVAS_NODE"; \
  else \
    echo "canvas.node NOT found with pattern $CANVAS_PATH_PATTERN"; \
    echo "Listing contents of potential canvas directories:"; \
    ls -R /app/node_modules/.pnpm/canvas@* || echo "Failed to list canvas directories in .pnpm"; \
  fi
  '''
]

[phases.start]
cmd = 'pnpm start'