[phases.setup]
nixPkgs = [
  'ffmpeg',
  'nodejs_20', # Provides the 'corepack' command itself
  'pnpm',      # Explicitly install pnpm via Nix
  'pkg-config', # Required by canvas
  'cairo',      # Required by canvas
  'pango',      # Required by canvas
  'libjpeg',    # Required by canvas
  'giflib',     # Required by canvas
  'librsvg',    # Required by canvas
  'python3',    # For node-gyp
  'gcc'         # For node-gyp / C++ compilation
]

[phases.install]
cmds = [
  'echo "Nixpacks Install Phase Start" ',
  'echo "Current PATH is: $PATH" ',
  'echo "Attempting to find pnpm with which:" ',
  'which pnpm || echo "pnpm not found by which" ',
  'echo "Attempting pnpm version check:" ',
  'pnpm --version || echo "pnpm --version failed" ',
  'echo "Attempting pnpm install --frozen-lockfile" ',
  'pnpm install --frozen-lockfile'
]

[phases.start]
# Assuming your package.json has "scripts": { "start": "node bot.js" }
# If not, Nixpacks will likely try 'node bot.js' or similar based on main field.
cmd = 'pnpm start'